개선
koreanbots/verification pull request #22
Opened 2021-07-11 03:46 UTC by wonderlandpark

2021-07-12 05:41 UTC, zero734kr requested changes

2021-07-12 05:41 UTC, zero734kr commented on README.md
>  ## 더 이상 봇 인증을 받지 않습니다.
why didn't you remove it?

2021-07-12 05:41 UTC, zero734kr commented on README.md
> +- 유저가 지원받을 수 있는 방법이 존재
```suggestion
- 유저가 공식적인 지원 통로(웹사이트, 티켓 채널 등)를 통해 문의할 수 있는 방법이 존재
```

2021-07-12 05:41 UTC, zero734kr commented on README.md
> +- 수집하는 개인정보와 이용범위를 서비스에 명시
```suggestion
- 수집하는 개인정보, 이용범위, 제 3자 위탁 업체를 유저가 접근 가능한 약관에 명시

2021-07-12 05:41 UTC, zero734kr commented on README.md
> +- 평균 90퍼센트 이상의 업타임
I think 95% would be better

2021-07-12 05:41 UTC, zero734kr commented on README.md
> +- 안전하고 신뢰할 수 있는 저장방식
```suggestion
- 안전하고 신뢰할 수 있는 개인 정보 같은 데이터의 저장 방식
```

2021-07-12 05:41 UTC, zero734kr commented on README.md
> +- 디스코드 인증된 봇
```suggestion
디스코드에게 인증된 봇
```

2021-07-12 05:41 UTC, zero734kr commented on README.md
> +- 봇의 Vanity URL, 배너, 배경 커스터마이징
```suggestion
- 봇의 전용 고유 URL, 배너와 배경 커스터마이징
```

2021-07-12 05:41 UTC, zero734kr commented on README.md
> +- 인증된 봇이여도, 당사는 어떠한 보증과 책임을 일체 부인합니다.
```suggestion
- 인증된 봇임에도 불구하고 봇 또는 봇의 개발자가 사회적 또는 도의적 물의를 일으킬 경우 인증된 봇 자격 박탈 외에는 어떠한 보증과 책임을 일체 부인합니다.
```

2021-07-12 05:41 UTC, zero734kr commented on README.md
> +- 인증된 봇은 당사와 어떠한 관련이 있지 않음을 밝힙니다.
```suggestion
```

2021-07-12 05:41 UTC, zero734kr commented on README.md
> +- 추후 기준이 변경되어도 가이드라인을 위반하지 않는 한 신뢰된 봇 자격이 박탈되지는 않습니다.
```suggestion
- 당사는 가이드라인 및 이용자들에게 물의를 일으켜 봇에 대한 신뢰성에 심각한 타격을 줄 경우 신뢰된 봇 자격을 박탈할 권한을 갖습니다.
```

2021-07-12 05:41 UTC, zero734kr commented on README.md
> +- 당사는 공개된 기준 이외에 내부 심사를 통해 승인 여부를 결정합니다.
```js
- 당사는 공개된 조건 이외에 봇에 대한 신뢰성을 보장할 수 있는지 대한 내부 심사를 통해 승인 여부를 결정합니다.
```

2021-08-28 13:33 UTC, kijk2869 approved these changes

2021-08-28 14:09 UTC, zero734kr requested changes

2021-08-28 14:09 UTC, zero734kr commented on .github/ISSUE_TEMPLATE/submit.yml
> +description: 봇 인증을 신청합니다.
```suggestion
description: 봇의 인증을 신청합니다.
```

2021-08-28 14:09 UTC, zero734kr commented on .github/ISSUE_TEMPLATE/submit.yml
> +title: 봇 이름으로 변경해주세요
```suggestion
title: (봇 이름으로 변경해주세요)
```

2021-08-28 14:09 UTC, zero734kr commented on .github/ISSUE_TEMPLATE/submit.yml
> +      description: 개인정보에 관한 안내는 서비스에 어떻게 안내되어 있나요? 또한 개인정보취급방침을 기재해주세요!
```suggestion
      description: 개인정보에 관한 안내는 서비스에 어떻게 안내되어 있나요? 또한 개인정보 취급 방침을 기재해주세요!
```

2021-08-28 15:55 UTC, zero734kr approved these changes

2021-08-28 15:55 UTC, merged